# Generated by Django 3.2.6 on 2021-08-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(upload_to='staticfiles/slider/%Y/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='staticfiles/team/%Y/%m/%d/'),
        ),
    ]
