# Generated by Django 3.2.6 on 2021-08-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0004_alter_youtuber_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='photo',
            field=models.ImageField(upload_to='media/ytubers/%Y/%m'),
        ),
    ]
